import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { writeFileSync } from 'node:fs';
import * as sass from 'sass';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// Compile styles.scss -> styles.css with the dart-sass compiler.
// (esbuild has no SCSS support; its css loader passes $vars through raw.)
function compileStyles() {
  const result = sass.compile('styles.scss', {
    style: prod ? 'compressed' : 'expanded',
    sourceMap: prod ? false : true,
    sourceMapIncludeSources: true,
  });
  let css = result.css;
  if (result.sourceMap) {
    // Inline the source map so dev tools can trace rules back to the .scss.
    const map = JSON.stringify(result.sourceMap);
    css += `\n/*# sourceMappingURL=data:application/json;base64,${Buffer.from(map).toString('base64')} */`;
  }
  writeFileSync('styles.css', css);
  console.log(`styles.scss -> styles.css (${css.length} bytes)`);
}

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtinModules,
  ],
  format: 'cjs',
  target: 'es2021',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  minify: prod,
});

if (prod) {
  compileStyles();
  await context.rebuild();
  process.exit(0);
} else {
  compileStyles();
  // esbuild watches the JS; a tiny fs watcher recompiles the SCSS on change.
  const { watch } = await import('node:fs');
  watch('styles.scss', () => compileStyles());
  await context.watch();
}